[package]
name = "bro"
version = "0.1.3"
edition = "2024"
readme = "README.md"
license = "MIT OR Apache-2.0"
authors = [ "Hitaishi V <hello@hitaishiv.com>" ]
description = "CLI shorcut tool to open/search on different websites on your browser."

[dependencies]
clap = { version = "4.5.36", features = ["cargo", "derive"] }
